-- liquibase formatted sql

-- changeSet Vladislav:2
create table person(
    id int generated by default as identity primary key,
    name varchar(100) not null ,
    middle_name varchar(100) not null ,
    last_name varchar(100) not null ,
    mail varchar(50) not null ,
    password varchar not null ,
    date_of_birth date not null ,
    status varchar not null ,
    role varchar not null
);
-- rollback drop table person;