-- liquibase formatted sql

-- changeSet Vladislav:9
create table assessment(
    id int generated by default as identity primary key,
    person_id int references person(id) not null,
    movie_id int references movie(id) not null,
    value int check ( value > 0 and value < 11)
);
-- rollback drop table assessment;