-- liquibase formatted sql

-- changeSet Vladislav:4
create table employee(
    id int generated by default as identity primary key,
    post_id int references post(id) on delete cascade,
    name varchar(20) not null,
    middle_name varchar(20) not null,
    lastname varchar(20) not null,
    date_of_birth date not null
);
-- rollback drop table employee;