-- liquibase formatted sql

-- changeSet Vladislav:7
create table image(
    id int generated by default as identity primary key,
    person_id int references person(id) unique,
    movie_id int references movie(id),
    employee_id int references employee(id) unique,
    url varchar
);
-- rollback drop table image;